#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml

types:
  # COMMENT:
  # This object is not part of GSIM. This object is a GSIM extension (plugin)
  # for use in Statistics Norway.
  About:
    description: Information about the model
    displayName: About

    properties:
      model_version:
        type: string
        default: "0.7"
        description: This version nested ProcessStepInstance inside the CodeBlocks attribute of ProcessStep
        displayName: Current model version
