#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  Doc: ./annotation/Doc.raml

types:
  # COMMENT:
  # This object is not part of GSIM. This object is a GSIM extension (plugin)
  # for use in Statistics Norway.
  About:
    description: Information about the model
    displayName: About

    properties:
      model_version:
        type: string
        default: "0.9"
        description: This version adds shortName to all objects and dataType to InstanceVariable
        displayName: Current model version
