#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:

  BusinessFunction:
    description: Something an enterprise does, or needs to do, in order to achieve its objectives.
    displayName: Business function
    type: IdentifiableArtefact.IdentifiableArtefact



    #example: !include ../examples/BusinessFunctionExample.json

