#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  Doc: ./annotation/Doc.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  ChangeDefinition:
    (Doc.objectGsimGroup): BUSINESS
    description: A structured, well-defined specification for a proposed change.
    displayName: Change definition
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
      populations?:
        type: string[]
        displayName: Populations
        (Link.types): [Population]

    #TODO: Why link only to Population ? Must consider more links here.
