#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  Doc: ./annotation/Doc.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ExchangeChannel: ./abstract/ExchangeChannel.raml

types:
  DataHarvesting:
    (Doc.objectGsimGroup): EXCHANGE
    description: A concrete and usable tool to gather information from the Internet.
    displayName: DataHarvesting
    type: [ IdentifiableArtefact.IdentifiableArtefact, ExchangeChannel.ExchangeChannel ]

    properties:
      dataHarvestingType:
        type: string
        description: Method for harvesting data
        displayName: Data harvester type
        enum:
          - API
          - WEBSCRAPING

    example: !include ../examples/_main/DataHarvesting_ShipRegisterNISNOR.json
