#%RAML 1.0 Library
uses:
  Doc: ./annotation/Doc.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ValueDomain: ./abstract/ValueDomain.raml

types:
  EnumeratedValueDomain:
    (Doc.objectGsimGroup): CONCEPT
    (Doc.objectMicroService): CONCEPT
    description: A Value Domain expressed as a list of Categories and associated Codes.
    displayName: Enumerated value domain
    type: [ IdentifiableArtefact.IdentifiableArtefact, ValueDomain.ValueDomain ]

    properties:
      klassUrl:
        type: string
        description: The url to KLASS codelist.
        displayName: Klass url

    # Notes:
    # KLASS (Statistics Norways system for classifications and Codelists) is also based on GSIM,
    # and will hopefully in the future be a part of the RAML spesifications of this project.

    example: !include ../examples/_main/EnumeratedValueDomain_Family.json
