#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  Doc: ./annotation/Doc.raml

types:
  # COMMENT:
  # This object is not part of GSIM. This object is a GSIM extension (plugin)
  # for use in Statistics Norway.
  MappingRawDataToInputData:
    (Doc.objectGsimGroup): OTHER
    description: Mapping elements from external Raw Data Object Store to Input Data (InstanceVariable).
    displayName: Mapping Raw data to Input data

    properties:
      id:
        type: string
        description: Global unique identifier (GUID).
        displayName: Id

      sourceName:
        type: string
        description: The name of the raw data source-element/field/variable (e.g. streetName or streetNumber)
        displayName: Raw data element name (or id)

      sourcePath:
        type: string
        description: Path to the raw data source-element/field/variable (e.g. Xpath /person/address/)
        displayName: Raw data source path

      targetInstanceVariable:
        type: string
        displayName: Target input data InstanceVariable (id)
        (Link.types): [InstanceVariable]

      validFrom?:
          type: datetime
          description: The date on which the mapping is effective or valid. Set this date only once (constant).
          displayName: Valid from

      validUntil?:
          type: datetime
          description: The date on which the mapping is no longer effective or valid.
          displayName: Valid until

      lastUpdatedDate?:
        type: datetime
        description: The date on which the object was created or updated.
        displayName: Last updated dat

      lastUpdatedBy?:
        type: string
        description: Created or updated by.
        displayName: Last updated by
        #TODO: link to Agent (id/guid)!

    example: !include ../examples/_main/MappingRawDataToInputData_PersonIncome.json
