#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  MeasurementType:
    description: The Measurement Type defines the type of a measure e.g. mass or currency. The Measurement Type groups all Measurement Units, which can be converted into each other. A Measurement Type can have a standard Measurement Unit, which can be used for conversion between different Measurement Units.
    displayName: Measurement type
    type:  IdentifiableArtefact.IdentifiableArtefact

    properties:

    example: !include ../examples/_main/MeasurementType_Currency.json
