#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  Doc: ./annotation/Doc.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  ProcessStepInstance:
    (Doc.objectGsimGroup): BUSINESS
    description: An executed step in a Business Process. A Process Step Instance specifies the actual inputs to and outputs from for an occurrence of a Process Step.
    displayName: Process step instance
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
      processExecutionCode:
        type: string
        displayName: Process execution code
        description: The action that took place as executable code

      parameterInputs?:
        type: string[]
        displayName: Parameter inputs
        (Link.types): [ParameterInput]

      transformableInputs?:
        type: string[]
        displayName: Transformable inputs
        (Link.types): [TransformableInput]

      processSupportInputs?:
        type: string[]
        displayName: Process support inputs
        (Link.types): [ProcessSupportInput]

      transformedOutputs?:
        type: string[]
        displayName: Transformed outputs
        (Link.types): [TransformedOutput]

      processMetrics?:
        type: string[]
        displayName: Process metrics
        (Link.types): [ProcessMetric]

      processExecutionLog:
        type: string
        displayName: Process execution log
        (Link.types): [ProcessExecutionLog]

    example: !include ../examples/_main/ProcessStepInstance_Test.json
