#%RAML 1.0 Library
uses:
  Doc: ./annotation/Doc.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ProcessOutput: ./abstract/ProcessOutput.raml

types:
  ProcessMetric:
    (Doc.objectGsimGroup): BUSINESS
    description: A Process Output whose purpose is to measure and report some aspect of how the Process Step performed during execution.
    displayName: Process metric
    type: [ IdentifiableArtefact.IdentifiableArtefact, ProcessOutput.ProcessOutput ]

    properties:

    #example: !include ../examples/Processmetric.json
