#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:

  RecordRelationship:
    description: Describes relationships between Logical Records within a Unit Data Structure. It must have both a source Logical Record and a target Logical Record in order to define the relationship.
    displayName: Record relationship
    type:  IdentifiableArtefact.IdentifiableArtefact

    properties:
      relationType:
        type: string
        description: The type of relation
        displayName: Relation type
        enum:
          - PARENT  # The source object is the parent of the target object. The target object is a sub-part or member of the parent source.
          - CHILD   # The source object is the child of the target object. The target object is the parent or contains the source object as a sub-part or member.
          - SIBLING # The source object is the sibling of the target object. One object is not a member of or subsidiary to the other. They may be equal members of the same group.
          - UNKNOWN # "Unknown" # The relationship between the source and target objects is unknown.

      sourceLogicalRecords:
        type: string[]
        displayName: Source logical records
        (Link.types): [LogicalRecord]

      targetLogicalRecords:
        type: string[]
        displayName: Target logical records
        (Link.types): [LogicalRecord]

    example: !include ../examples/_main/RecordRelationship_Family_Person.json
