#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  SubjectField:
    description: One or more Concept Systems used for the grouping of Concepts and Categories for the production of statistics.
    displayName: Subject field
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:
      parentSubjectField?:
        type: string
        displayName: Parent subject field
        (Link.types): [SubjectField]
    example: !include ../examples/_main/SubjectField_IncomeAndWealth.json
