#%RAML 1.0 Library
uses:
  Doc: ./annotation/Doc.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml

types:
  SubjectField:
    (Doc.objectGsimGroup): CONCEPT
    (Doc.objectMicroService): CONCEPT
    description: One or more Concept Systems used for the grouping of Concepts and Categories for the production of statistics.
    displayName: Subject field
    type: IdentifiableArtefact.IdentifiableArtefact

    properties:

    example: !include ../examples/_main/SubjectField_IncomeAndWealth.json
