#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ProcessInput: ./abstract/ProcessInput.raml
types:

  TransformableInput:
    description: A type of Process Input whose content goes into a Process Step and is changed in some way by the execution of that Process Step. Some or all of the content will be represented in the Transformed Output.
    displayName: Transformable input
    type: [IdentifiableArtefact.IdentifiableArtefact, ProcessInput.ProcessInput]
    properties:

    #example: !include ../examples/TransformableInput.json

