#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ProcessInput: ./abstract/ProcessInput.raml

types:
  TransformableInput:
    description: A type of Process Input whose content goes into a Process Step and is changed in some way by the execution of that Process Step. Some or all of the content will be represented in the Transformed Output.
    displayName: Transformable input
    type: [ IdentifiableArtefact.IdentifiableArtefact, ProcessInput.ProcessInput ]

    properties:
      inputId:
        type: string
        displayName: Input id
        (Link.types): [UnitDataSet, DimensionalDataSet]

      inputAlias?:
        type: string
        displayName: Resource alias 
        description: Alias used in code when referring to the resource

    example: !include ../examples/_main/TransformableInput_Example.json

