#%RAML 1.0 Library
uses:
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  ProcessOutput: ./abstract/ProcessOutput.raml
types:

  TransformedOutput:
    description: A Process Output (a result) which provides the reason for existence for the Process Step.
    displayName: Transformed output
    type: [IdentifiableArtefact.IdentifiableArtefact, ProcessOutput.ProcessOutput]
    properties:

    #example: !include ../examples/TransformedOutput.json
