#%RAML 1.0 Library
uses:
  Link: ./annotation/Link.raml
  IdentifiableArtefact: ./abstract/IdentifiableArtefact.raml
  Concept: ./abstract/Concept.raml

types:
  Universe:
    description: A defined class of people, entities, events, or objects, with no specification of time and geography, contextualizing a Unit Type.
    displayName: Universe
    type: [ IdentifiableArtefact.IdentifiableArtefact, Concept.Concept ]

    properties:
      unitTypes:
        type: string[]
        displayName: Unit types
        (Link.types): [UnitType]

    example: !include ../examples/_main/Universe_Family.json
