#%RAML 1.0 Library
types:

  AgentDetails:
    description: A generic and expandable key-value-store for adding present and future AgentDetails-attributes to the Agent-object.
    type: object

    properties:
      agentDetailType:
        type: string
        description: The type (key) of the AgentDetails-attribute.
        displayName: Agent detail type
        enum:
          - CONTACT_EMAIL
          - CONTACT_MOBILE
          - CONTACT_PHONE
          - CONTACT_ADDRESS
      values:
        type: string[]
        description: One or more values (a list) for this agentDetailType.
        displayName: Values
