#%RAML 1.0 Library
uses:

types:

  ProcessInput:
    description: Any instance of an information object which is supplied to a Process Step Instance at the time its execution is initiated.

    properties:
